---

 - name: Ensure apt cache is up to date
   apt: update_cache=yes
   become: yes

 - name: Ensure packages are installed
   apt: name={{item}}
   become: yes
   with_items:
     - postgresql
     - libpq-dev
     - python-psycopg2

 - name: Ensure database is created
   postgresql_db: name={{database_name}}
   become_user: postgres
   become: yes

 - name: Ensure user has access to database
   postgresql_user: >
     db={{database_name}}
     name={{database_user}}
     password={{database_password}}
   become_user: postgres
   become: yes

 - name: Copy postgresql.conf settings
   template: >
     src=postgresql.conf.j2
     dest=/etc/postgresql/9.3/main/postgresql.conf
   become: yes
   notify:
     - Restart PostgreSQL

 - name: Write pg_hba.conf settings
   template: >
     src=pg_hba.conf.j2
     dest=/etc/postgresql/9.3/main/pg_hba.conf
   become: yes
   notify:
     - Restart PostgreSQL
