# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[(b'win1', b'Player 1 wins'), (b'win2', b'Player 2 wins'), (b'draw', b'Draw'), (b'in_progress', b'In progress')], default=b'in_progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
