# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160413_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together=set([('game', 'x', 'y', 'player')]),
        ),
    ]
