---

 - name: Ensure apt cache is up to date
   apt: update_cache=yes
   become: yes

 - name: Ensure web server packages are installed
   apt: name={{item}}
   become: yes
   with_items:
     - git
     - htop
     - libfreetype6
     - libfreetype6-dev
     - libjpeg8
     - libjpeg62-dev
     - libpng-dev
     - libxft-dev
     - nginx
     - nodejs-legacy
     - npm
     - python-dev
     - python-imaging
     - python-psycopg2
     - python-virtualenv

 - name: Install bower
   npm:
     name=bower
     global=yes
     version=1.6.5
   become: yes
