- name: Restart NGINX
  service: name=nginx state=restarted
  become: yes

- name: Restart Gunicorn
  service: name={{gunicorn_name}} state=restarted
  become: yes

- name: Restart Crontab
  service: name=cron state=restarted
  become: yes
