---

- name: Set ENV variable for DJANGO_SETTINGS_MODULE
  lineinfile:
    dest: {{env_variables_file}}
    line: DJANGO_SETTINGS_MODULE="{{django_settings_module}}"
    state: present

- name: Set ENV variable for SECRET_KEY
  lineinfile:
    dest: {{env_variables_file}}
    line: SECRET_KEY="{{secret_key}}"
    state: present

- name: Set ENV variable for DATABASE_NAME
  lineinfile:
    dest: {{env_variables_file}}
    line: DATABASE_NAME="{{database_name}}"
    state: present

- name: Set ENV variable for DATABASE_USER
  lineinfile:
    dest: {{env_variables_file}}
    line: DATABASE_USER="{{database_user}}"
    state: present

- name: Set ENV variable for DATABASE_PASSWORD
  lineinfile:
    dest: {{env_variables_file}}
    line: DATABASE_PASSWORD="{{database_password}}"
    state: present

- name: Set ENV variable for DATABASE_HOST
  lineinfile:
    dest: {{env_variables_file}}
    line: DATABASE_HOST="{{database_host}}"
    state: present

- name: Enable virtual environment when a user logs in
  lineinfile:
    dest: /home/{{ansible_ssh_user}}/.bashrc
    line: source {{virtualenv_dir}}/bin/activate