---

- name: Check if virtualenv already exists
  stat: path={{virtualenv_dir}}
  register: venv_dir

- name: Create virtualenv for Django web application if it doesn't exist
  shell: virtualenv {{virtualenv_dir}}
  when: venv_dir.stat.isdir is not defined

- name: Create log folder if it doesn't exist
  file:
    path={{log_dir}}
    state=directory

- name: Checkout latest web app code from Github
  git: >
    repo={{project_repo}}
    dest={{project_root}}
    accept_hostkey=True
    version={{branch}}
  tags:
    - checkout_from_github
  notify:
    - Restart Gunicorn
    - Restart Crontab

- name: Create components folder if it doesn't exist
  file:
    path={{project_root}}/components
    state=directory

- name: Install web application dependencies listed in requirements.txt
  pip: >
    requirements={{requirements_file}}
    virtualenv={{virtualenv_dir}}

- name: Check if app/static directory exists
  stat: path={{project_root}}/static
  register: static_dir

- name: Create a static directory for Django app if it does not exist
  file: path='{{project_root}}/static' state=directory
  when: static_dir.stat.isdir is not defined

- name: Migrate database schema
  django_manage:
    command=migrate
    app_path={{project_root}}
    virtualenv={{virtualenv_dir}}
  environment:
    - SECRET_KEY: "{{secret_key}}"
    - DATABASE_NAME: "{{database_name}}"
    - DATABASE_USER: "{{database_user}}"
    - DATABASE_PASSWORD: "{{database_password}}"
    - DATABASE_HOST: "{{database_host}}"
    - DJANGO_SETTINGS_MODULE: "{{django_settings_module}}"

- name: Run bower update.
  django_manage: >
    command="bower install"
    app_path={{project_root}}
    virtualenv={{virtualenv_dir}}
  notify:
    - Restart Gunicorn
  environment:
    - SECRET_KEY: "{{secret_key}}"
    - DATABASE_NAME: "{{database_name}}"
    - DATABASE_USER: "{{database_user}}"
    - DATABASE_PASSWORD: "{{database_password}}"
    - DATABASE_HOST: "{{database_host}}"
    - DJANGO_SETTINGS_MODULE: "{{django_settings_module}}"

- name: Django collectstatic
  django_manage: >
    command="collectstatic"
    app_path={{project_root}}
    virtualenv={{virtualenv_dir}}
  environment:
    - SECRET_KEY: "{{secret_key}}"
    - DATABASE_NAME: "{{database_name}}"
    - DATABASE_USER: "{{database_user}}"
    - DATABASE_PASSWORD: "{{database_password}}"
    - DATABASE_HOST: "{{database_host}}"
    - DJANGO_SETTINGS_MODULE: "{{django_settings_module}}"
  tags: collectstatic
  notify:
    - Restart Gunicorn
    - Restart NGINX
