---

- name: Check if /var/log/gunicorn folder exists
  file:
    path=/var/log/gunicorn
    owner={{ansible_ssh_user}}
    group={{ansible_ssh_user}}
    mode=755
    state=directory
  become: yes

- name: Write upstart script for gunicorn
  template: src=gunicorn.conf.j2 dest=/etc/init/{{gunicorn_name}}.conf force=yes
  become: yes
  notify:
    - Restart Gunicorn
